-- FZF
-- FZF maps
-- vim.keymap.set("n", ",,", ":Commands<CR>")
-- vim.keymap.set("n", ",.", ":History:<CR>")
-- vim.keymap.set("n", ",/", ":Rg<CR>")
-- vim.keymap.set("n", "<C-p>", ":Files<CR>")
-- vim.keymap.set("n", "<C-e>", ":Buffers<CR>")
-- vim.keymap.set("n", "<C-n>", ":Notes<CR>")
